project:
  type: website

website:
  title: "Brunarmattos"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: vapor
    css: styles.css

editor: visual

comments:
  giscus:
    repo: Brunarmattos/Brunarmattos1

